<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_GroupElement" Id="{beeb3d35-878d-4bf3-be89-bef516a524fb}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_GroupElement EXTENDS FB_BaseGroupElement IMPLEMENTS ITF_GroupElement, ITF_GroupElement_HMI_Init
VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>