<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_IOSensor_NC" Id="{66f34a47-e680-4956-881b-083b97d3eeed}" SpecialFunc="None">
    <Declaration><![CDATA[(*			
	EVERDE sp. z o.o.
	Rafał Osajda		22.01.2025		TC 4026.13		wer. 0.0.0.1
	B_Baza dla czujników binarnych styk normalnie zamkniety 	
*)
FUNCTION_BLOCK FB_IOSensor_NC EXTENDS FB_IOSensor
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{834e05af-13c9-4454-a99d-74f1de00ecd0}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^.eType		:= E_IOSensorType.NC;
]]></ST>
      </Implementation>
    </Method>
    <Method Name="IsActive" Id="{f7918a5a-9f4d-4c0c-9ba4-df583fdafefe}">
      <Declaration><![CDATA[(*			
	EVERDE sp. z o.o.
	Rafał Osajda		05.02.2025		TC 4026.13		wer. 0.0.0.1
	Zwraca aktualny stan czujnika
*)
METHOD IsActive : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[IsActive				:= NOT THIS^.bContact;
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>