<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_HMIConfiguration" Id="{815a9dbf-7990-4d6d-af4f-3263d1132175}" SpecialFunc="None">
    <Declaration><![CDATA[(*			
	RafalOS
	Rafał Osajda		10.11.2025		TC 4024.66
	Główny blok konfigurujący HMI
*)
FUNCTION_BLOCK FB_HMIConfiguration EXTENDS FB_Base IMPLEMENTS ITF_HMIConfiguration
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="AddElements" Id="{7302c3e8-1e13-4369-a5d6-2e8b1d6b4005}">
      <Declaration><![CDATA[(*			
	RafalOS
	Rafał Osajda		13.11.2025		TC 4024.66
	Metoda przeznaczona do dodawania elementów do FB_HMIManager
*)
METHOD AddElements : BOOL
VAR_INPUT
	itfHMIManager	: B_HMI_Manager.ITF_HMIManagerConfigure;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>