<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="PRG_Compilation" Id="{1360e8a4-0d65-02a4-26da-1d595118164a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_Compilation
VAR
	fbLabel					: FB_BaseLabel;
	fbDescription			: FB_BaseDescriptor;
	fbLocation				: FB_BaseLocation;
	fbCommand				: FB_BaseCommand;
	fbImpuls				: FB_BaseImpulse;
	
	sttmpCommonData			: ST_BaseCommonData;

	fbBaseTime				: FB_BaseTime;
	fbBaseCommand			: FB_BaseCommand;
	fbBaseDescriptor		: FB_BaseDescriptor;
	fbBaseFlag				: FB_BaseFlag;
	fbBaseImplulse			: FB_BaseImpulse;
	fbBaseLocation			: FB_BaseLocation;
	
	fbBaseLogger			: FB_BaseLogger;
	fbBaseLoggerElement		: FB_BaseLoggerElement;
	fbBaseComponent			: FB_BaseComponent;
	fbBaseExecutiveElement	: FB_BaseControlElement;
	fbBaseComplexElement	: FB_BaseGroupElement;
	fbBaseMainComponent		: FB_BaseTopElement;
//B
	fbKomunikator		: FB_Komunikator;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>