<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_Component" Id="{2de1b166-2e29-435f-8ec0-de550667ad0a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Component EXTENDS FB_BaseComponent IMPLEMENTS ITF_Component, ITF_Component_HMI_Init
VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>