<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_BaseComplexElement" Id="{1f8518b0-2e03-0c13-2a4a-ffc3b6f9b887}" SpecialFunc="None">
    <Declaration><![CDATA[(*			
	RAFALOS
	Rafał Osajda		19.09.2025		TC 4024.66
	FB Bazowy dla wszystkich elementów złożonych
*)
FUNCTION_BLOCK FB_BaseComplexElement EXTENDS FB_BaseExecutiveElement IMPLEMENTS ITF_BaseComplexElement
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>