<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Group2" Id="{ff0c6652-1926-02a6-01b7-cfff6f7852b0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Group2 EXTENDS FB_BaseGroupElement IMPLEMENTS ITF_Group1, ITF_Group2_HMI_Connector
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>