<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_CommandChangeSuspend" Id="{48484d22-ae57-0719-2adb-4a264957724b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_CommandChangeSuspend EXTENDS FB_CommandChange IMPLEMENTS ITF_CommandChange
VAR

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Execute" Id="{46fd99ba-f496-0e35-0fe5-7385caa24cf7}">
      <Declaration><![CDATA[METHOD Execute : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>