<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_CommandChangeUnSuspend" Id="{03c9589a-fc15-0c4a-14e8-fb8dbfc85e4c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_CommandChangeUnSuspend IMPLEMENTS ITF_CommandChange
VAR

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Execute" Id="{af28a0de-e214-001a-3556-df82a40ec4e4}">
      <Declaration><![CDATA[METHOD Execute : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>