<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Sensor_TestParentDecorator" Id="{67645e76-427e-4501-bf87-8b0f905c7add}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT FB_Sensor_TestParentDecorator EXTENDS FB_BaseComponentDecoratorParent IMPLEMENTS ITF_Sensor_TestDecorator
VAR
	bContactTest			: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="IsActive" Id="{d21918fa-2e53-0edb-3f50-08a193727751}">
      <Declaration><![CDATA[(*			
	EVERDE sp. z o.o.
	Rafał Osajda		05.02.2025		TC 4026.13		wer. 0.0.0.1
	Zwraca aktualny stan czujnika
*)
METHOD IsActive : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="SetContact" Id="{2400656c-d1fa-4d75-9e59-2914639345c5}">
      <Declaration><![CDATA[METHOD PUBLIC SetContact
VAR_INPUT
	bIN: BOOL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^.bContactTest		:= bIN;
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>