<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Group3" Id="{99d9d65a-afa1-06bb-2b27-2fdb5a993c98}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Group3 EXTENDS FB_BaseGroupElement IMPLEMENTS ITF_Group1, ITF_Group3_HMI_Connector
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>