<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_SITP_PolecenieZmianyTrybu" Id="{88981f86-59cf-0c0f-1328-7e75c01eeeb2}" SpecialFunc="None">
    <Declaration><![CDATA[(*			
	EVERDE sp. z o.o.
	Rafał Osajda		25.02.2025		TC 4026.13		wer. 0.0.0.1
	FB odpowiedzialny za zmianę stanu
*)
FUNCTION_BLOCK FB_SITP_PolecenieZmianyTrybu EXTENDS FB_SITP_PolecenieZmiany IMPLEMENTS ITF_SITP_PolecenieZmianyTrybu
VAR
	ePolecenie			: E_SITP_PolecenieZmianyTrybu;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{61e45ddf-8de4-03e7-2cd2-88d978e7a20c}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	ePolecenie			: E_SITP_PolecenieZmianyTrybu;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^.ePolecenie		:= ePolecenie;
]]></ST>
      </Implementation>
    </Method>
    <Method Name="zwrocRodzajPolecenia" Id="{2683c92c-79bf-0147-3d5f-768f79c2f9ab}">
      <Declaration><![CDATA[METHOD PUBLIC zwrocRodzajPolecenia : E_SITP_PolecenieZmianyTrybu
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[zwrocRodzajPolecenia		:= THIS^.ePolecenie;
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>