<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_CommandChangeWashing" Id="{fc59e713-f62c-0b84-1e8c-cb2160191a08}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_CommandChangeWashing IMPLEMENTS ITF_CommandChange
VAR

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Execute" Id="{f8cf665e-c022-0227-07b6-bead78b58b71}">
      <Declaration><![CDATA[METHOD Execute : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>