<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_CommandChangeManual" Id="{cadad792-7390-0b42-30fc-c416ff868d87}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_CommandChangeManual IMPLEMENTS ITF_CommandChange
VAR

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Execute" Id="{b378863c-7780-0866-3e9e-58c3a8586b52}">
      <Declaration><![CDATA[METHOD Execute : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>