<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_CommandChangeDiagnostics" Id="{ed383c6a-d475-0169-01d9-89d0a8244ba2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_CommandChangeDiagnostics IMPLEMENTS ITF_CommandChange
VAR

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Execute" Id="{988757a1-ed85-080d-12ed-2884e52bb97a}">
      <Declaration><![CDATA[METHOD Execute : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>