<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_BaseLoggerElement" Id="{84ce134f-38cc-08bd-3d60-40e507799b32}" SpecialFunc="None">
    <Declaration><![CDATA[(*			
	RAFALOS
	Rafał Osajda		19.09.2025		TC 4024.66
	Element bazowy umożliwiający potomkom wysyłaś zgłoszenia do logera
*)
FUNCTION_BLOCK FB_BaseLoggerElement EXTENDS FB_BaseDescriptor IMPLEMENTS ITF_BaseLoggerElement
VAR
	refstCommonData			: REFERENCE TO ST_CommonData;


END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="Init" Id="{a43ff208-6465-0856-03a7-b9aebcd62c45}" />
    <Method Name="FB_init" Id="{97b134fe-0cbf-0c91-1da4-63b4d9677ccb}" FolderPath="Init\">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	refstCommonData			: REFERENCE TO ST_CommonData;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^.refstCommonData			REF= refstCommonData;
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>