<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="PRG_Compilation" Id="{b1995b4c-786d-03c5-204c-1db0d16f2c14}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_Compilation
VAR
	fbLoggerHMI				: FB_BaseHMILogger;
	fbLoggerElementHMIView	: FB_BaseHMILoggerElement_View;
	fbLoggerElementHMICmd	: FB_BaseHMILoggerElement_Command;
	fbComponentHMIView		: FB_BaseHMIComponent_View;
	fbComponentHMICmd		: FB_BaseHMIComponent_Command;
	fbControlElementHMIView	: FB_BaseHMIControlElement_View;
	fbControlElementHMICmd	: FB_BaseHMIControlElement_Command;
	fbGroupElementHMIView	: FB_BaseHMIGroupElement_View;
	fbGroupElementHMICmd	: FB_BaseHMIGroupElement_Command;
	fbTopElementHMIView		: FB_BaseHMITopElement_View;
	fbTopElementHMICmd		: FB_BaseHMITopElement_Command;
	
	fbRecipe				: FB_BaseRecipe;
	fbRecipeHMI				: FB_BaseRecipe_HMI (fbBaseRecipe := fbRecipe);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>