<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="PRG_Compilation" Id="{b1995b4c-786d-03c5-204c-1db0d16f2c14}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_Compilation
VAR
	fbLoggerHMI				: FB_BaseLogger_HMI;
	fbLoggerElementHMI		: FB_BaseLogger_HMI;
	fbComponentHMI			: FB_BaseComponent_HMI;
	fbExecutiveElementHMI	: FB_BaseControlElement_HMI;
	fbComplexElement		: FB_BaseGroupElement_HMI;
	fbMainComponent			: FB_BaseTopElement_HMI;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>