<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="PRG_ControlHMI" Id="{2dfd529a-8da9-0bb7-1a99-ad15ed92c2b8}" SpecialFunc="None">
    <Declaration><![CDATA[(*			
	RafalOS
	Rafał Osajda		10.11.2025		TC 4024.66
	Program sterowanie HMI
*)
PROGRAM PRG_ControlHMI
VAR
	(*	Główny element sterowania wyświetlaniem na HMI					*)
	fbHMIManager					: FB_HMIManager;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
	(*	Wywołanie metody sterowania HMI	*)

IF (GVL_Systemvariable.bDefaultInitDone AND
	GVL_Systemvariable.bMachineInitDone AND
	GVL_SystemVariable.bControlHMIInit AND
	GVL_SystemVariable.fbMachineControl.IsInitDone ()) THEN
	
	fbHMIManager ();
END_IF
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>