<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_MCHMIPrepareDataForScreen" Id="{3050d0c5-d80e-0889-00e3-5f0104bdd004}" SpecialFunc="None">
    <Declaration><![CDATA[(*			
	RafalOS
	Rafał Osajda		19.11.2025		TC 4024.66
	Domyślne przygotowanie danych dla ekranu
*)
FUNCTION_BLOCK FB_MCHMIPrepareDataForScreen EXTENDS FB_BaseComponent_HMI IMPLEMENTS ITF_MCHMIPrepareDataForScreen
VAR
	//itf do lacznika machinecontrol
	//strulture danych 
	//dodać ITF dla możliwości obsługi rozszerzonej obsługi wyświetlania 
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="ClearAfterScreen" Id="{9877e0d9-8678-0ae8-355c-333615fe32d2}">
      <Declaration><![CDATA[(*			
	RafalOS
	Rafał Osajda		19.11.2025		TC 4024.66
	Czyści danych przy zmienia ramki po poprzedniej ramce
*)
METHOD PUBLIC ClearAfterScreen : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[SUPER^.ClearAfterScreen ();
]]></ST>
      </Implementation>
    </Method>
    <Method Name="PrepareDataForHMI" Id="{bc2b143f-e4a1-0155-38ef-904b1a2f8b08}">
      <Declaration><![CDATA[(*			
	RafalOS
	Rafał Osajda		14.11.2025		TC 4024.66
	Metoda przygotowywania danych dla HMI 
	W niej odbywa się odpytywanie właściego elementu przez łącznik
*)
METHOD PUBLIC PrepareDataForHMI : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[SUPER^.PrepareDataForHMI ();
]]></ST>
      </Implementation>
    </Method>
    <Method Name="PrepareForScreen" Id="{28b2ca1f-8b84-0c44-1ac0-89ac26d6625e}">
      <Declaration><![CDATA[(*			
	RafalOS
	Rafał Osajda		19.11.2025		TC 4024.66
	Przygotowanie ramki pood tamke do wyświetlenia - tylko przygotowanie a nie przygotowanie danych do wyświetlenia
*)
METHOD PUBLIC PrepareForScreen : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[SUPER^.PrepareForScreen ();
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>