<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Przycisk_NC" Id="{67ab5e68-7c00-41fd-bce3-35b5b14f6170}" SpecialFunc="None">
    <Declaration><![CDATA[(*			
	EVERDE sp. z o.o.
	Rafał Osajda		31.01.2025		TC 4026.13		wer. 0.0.0.1
	Obsługa przycisku ze stykiem NC
*)
FUNCTION_BLOCK FB_Przycisk_NC EXTENDS FB_Przycisk
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Stan" Id="{10c67b5f-8f1a-4820-9165-12fe0c243f33}">
      <Declaration><![CDATA[(*			
	EVERDE sp. z o.o.
	Rafał Osajda		31.01.2025		TC 4026.13		wer. 0.0.0.1
	Zwraca stan przycisku
*)
METHOD Stan : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[Stan			:= NOT THIS^.bStyk;
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>