<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_BaseMainComponent_HMI" Id="{d9fb61e2-46e3-081a-2db2-ee62cb4cde2f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_BaseMainComponent_HMI EXTENDS FB_BaseComplexElement_HMI IMPLEMENTS ITF_BaseMainComponent_HMI
VAR
	itfBaseMainComponentConnector		: ITF_BaseMainComponent_HMI_Connector;
	refstBaseMainComponentDataHMI		: REFERENCE TO ST_BaseMainComponent_HMI;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>