<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_BaseFlag" Id="{4cccc323-b44e-0e45-096d-9e86741e033e}" SpecialFunc="None">
    <Declaration><![CDATA[(*			
	RAFALOS
	Rafał Osajda		19.09.2025		TC 4024.66
	
*)
FUNCTION_BLOCK FB_BaseFlag IMPLEMENTS ITF_BaseFlag
VAR
	bState				: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="GetFlag" Id="{7e86e6a8-5c6a-0c08-063a-dbd6b6149b83}">
      <Declaration><![CDATA[METHOD PUBLIC GetFlag : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[GetFlag			:= THIS^.bState;
]]></ST>
      </Implementation>
    </Method>
    <Method Name="SetFlag" Id="{37efbdda-7095-09eb-2668-2e143dcbc25c}">
      <Declaration><![CDATA[METHOD PUBLIC SetFlag
VAR_INPUT
	bState				: BOOL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^.bState			:= bState;
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>