<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="PRG_SystemControlMachineWork" Id="{79612be6-fc24-0aa2-1eaf-ef9f7362db8a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_SystemControlMachineWork
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[IF (PRG_SystemControlMachineInit.bFirstCycle) THEN
	(*	Wywołanie obsługi Logera	*)
	GVL_SystemVariable.fbLogger ();
	(*	Wywołanie pracy maszyny		*)
	GVL_SystemVariable.fbMachineControl ();
END_IF
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>