<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_DefaultTemplate" Id="{e2ee2d14-ecb4-01c4-306a-b65670566e82}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_DefaultTemplate EXTENDS FB_Base IMPLEMENTS ITF_BaseCreateTemplateOfRecipe
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="CreateTamplateOfRecipe" Id="{122e16dd-ac31-0a2f-15a7-70e584accb5c}">
      <Declaration><![CDATA[METHOD CreateTamplateOfRecipe : BOOL
VAR_INPUT
	(*interfejs do obsługi receptur*)
	itfRecipe	: B_Base.ITF_BaseCreatingTemplateMethod;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[(*	Metody tworzące szablon receptury 
	- dodanie nazwy i utworzenie szablonu 
	- dodawanie składników
*)]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>