<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_BaseComplexElement_HMI" Id="{3f198324-9925-0fb3-39d4-b6620e2a327f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_BaseComplexElement_HMI EXTENDS FB_BaseExecutiveElement_HMI IMPLEMENTS ITF_BaseComplexElement_HMI
VAR
	itfBaseComplexElementConnector		: ITF_BaseComplexElement_HMI_Connector;
	refstBaseComplexElementDataHMI		: REFERENCE TO ST_BaseComplexElement_HMI;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>