<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_ControlElement" Id="{e992bc3e-7895-4c18-b6c0-85825d004486}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ControlElement EXTENDS FB_BaseControlElement IMPLEMENTS ITF_ControlElement, ITF_ControlElement_HMI_Init
VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>