<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_BaseMainComponent" Id="{b23ea2e3-7979-0bc9-362e-7cf0941731d6}" SpecialFunc="None">
    <Declaration><![CDATA[(*			
	RAFALOS
	Rafał Osajda		19.09.2025		TC 4024.66
	Rodzic dla wszystkich podzespołów głównych w maszynie 
*)
FUNCTION_BLOCK FB_BaseMainComponent EXTENDS FB_BaseComplexElement IMPLEMENTS ITF_BaseMainComplex
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>