<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="PRG_Compilation" Id="{e3d1aff8-90e2-4b06-bf62-3f7b8a8c4d92}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_Compilation
VAR
	fbCzujnikNC					: FB_IOSensor_NC;
	fbCzujnikNO					: FB_IOSensor_NO;
	fbCzujnik2xNO				: FB_IOSensor_NO_2InRow;
	fbELekrozawor3na2_NC		: FB_IOElectrovalve_3on2_NC;
	fbELekrozawor3na2_NO		: FB_IOElectrovalve_3on2_NO;
	fbELekrozawor5na2_1C		: FB_IOElectrovalve_5on2_1Coil;
	fbELekrozawor5na2_2C		: FB_IOElectrovalve_5on2_2Coil;
	fbELekrozawor5na2_2C_Odp	: FB_IOElectrovalve_5on3_2Coil_Vented;
	fbELekrozawor5na2_2C_Zap	: FB_IOElectrovalve_5on3_2Coil_Infected;
	fbLampka					: FB_IOLamp;
	fbLampkaRozszerzona			: FB_IOLampBlinking;
	fbPrzyciskNC				: FB_IOButton_NC;
	fbPrzyciskNO				: FB_IOButton_NO;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>