<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_TopElement_HMI" Id="{54abd47c-3eb0-49fb-a4d6-79dd6427523e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TopElement_HMI EXTENDS FB_BaseTopElement_HMI IMPLEMENTS ITF_TopElement_HMI
VAR
	itfMainElementConnector				: ITF_TopElement_HMI_Connector;
	refstMainElementData				: REFERENCE TO ST_TopElement_HMI;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>