<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_BaseTime" Id="{aefd6312-b514-007c-3d1e-139902c0f3f6}" SpecialFunc="None">
    <Declaration><![CDATA[(*			
	RAFALOS
	Rafał Osajda		19.09.2025		TC 4024.66
	Obsługa czasu w systemie
*)
FUNCTION_BLOCK FB_BaseTime IMPLEMENTS ITF_BaseTime
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>