<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_BaseTopElement" Id="{b23ea2e3-7979-0bc9-362e-7cf0941731d6}" SpecialFunc="None">
    <Declaration><![CDATA[(*			
	RAFALOS
	Rafał Osajda		19.09.2025		TC 4024.66
	Rodzic dla wszystkich podzespołów głównych w maszynie 
*)
FUNCTION_BLOCK FB_BaseTopElement EXTENDS FB_BaseGroupElement IMPLEMENTS ITF_BaseTopElement, ITF_BaseTopElement_HMI_Connector
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{8200787b-ee94-0c86-2812-2a65b9019324}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^.stIdentifier.eType			:= E_BaseElementType.eTop;
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>