<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_BaseTopElement" Id="{b23ea2e3-7979-0bc9-362e-7cf0941731d6}" SpecialFunc="None">
    <Declaration><![CDATA[(*			
	RAFALOS
	Rafał Osajda		19.09.2025		TC 4024.66
	Rodzic dla wszystkich podzespołów głównych w maszynie 
*)
FUNCTION_BLOCK FB_BaseTopElement EXTENDS FB_BaseGroupElement IMPLEMENTS ITF_BaseTopElement, ITF_BaseTopElement_HMI_Connector
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="ITF_DecoratedElement" Id="{882a84e3-bde0-0fb8-0f20-5da4c990e3e6}" />
    <Method Name="ExecuteEveryCycle_Error" Id="{7d7b831e-4b28-0c6d-1881-11fac660b25a}">
      <Declaration><![CDATA[(*			
	EVERDE sp. z o.o.
	Rafał Osajda		27.03.2025		TC 4024.66
	Obsluga bledow sprawdzanie czy jakis blad sie nei pojawil i ustawienie stanu lub wylaczenie
*)
METHOD PUBLIC ExecuteEveryCycle_Error
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[SUPER^.ExecuteEveryCycle_Error ();
]]></ST>
      </Implementation>
    </Method>
    <Method Name="ExecuteEveryCycle_Operation" Id="{841e6a4b-e4c1-0c2c-0e48-b22271ccf3c1}">
      <Declaration><![CDATA[(*			
	EVERDE sp. z o.o.
	Rafał Osajda		27.03.2025		TC 4024.66
	Wywolanie co cykl operacji 
*)
METHOD PUBLIC ExecuteEveryCycle_Operation
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[SUPER^.ExecuteEveryCycle_Operation ();
]]></ST>
      </Implementation>
    </Method>
    <Method Name="ExecuteEveryCycle_Status" Id="{8fc845d8-b98b-055f-14fd-7c549a782f93}">
      <Declaration><![CDATA[(*			
	EVERDE sp. z o.o.
	Rafał Osajda		27.03.2025		TC 4024.66
	Aktualizacja flag 
*)
METHOD PUBLIC ExecuteEveryCycle_Status
VAR_INST
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[SUPER^.ExecuteEveryCycle_Status ();
]]></ST>
      </Implementation>
    </Method>
    <Method Name="ExecuteEveryCycle_Test" Id="{836e6c96-252b-0639-239a-fc6d6e00c17d}">
      <Declaration><![CDATA[(*			
	EVERDE sp. z o.o.
	Rafał Osajda		27.03.2025		TC 4024.66
	Testowanie czy nei pojawil sie jakis rozkaz i uruchomienie odpowiednich operacji
*)
METHOD PUBLIC ExecuteEveryCycle_Test
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[SUPER^.ExecuteEveryCycle_Test ();
]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_init" Id="{8200787b-ee94-0c86-2812-2a65b9019324}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^.stIdentifier.eType			:= E_BaseElementType.eTop;
]]></ST>
      </Implementation>
    </Method>
    <Method Name="GetITFTopElement" Id="{24aceef8-2bfb-0d09-172c-478ecab1a9d8}" FolderPath="ITF_DecoratedElement\">
      <Declaration><![CDATA[METHOD GetITFTopElement : ITF_BaseTopElement
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[GetITFTopElement		:= THIS^;
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>