<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_BaseComponent_HMI" Id="{52a5d3de-74e5-09ff-1362-d8678f55ad3c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_BaseComponent_HMI EXTENDS FB_BaseLoggerElement_HMI IMPLEMENTS ITF_BaseComponent_HMI
VAR
	itfBaseComponentConnector			: ITF_BaseComponent_HMI_Connector;
	refstBaseComponentDataHMI			: REFERENCE TO ST_BaseComponent_HMI;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>