<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_BaseHMILogger" Id="{d0482a64-a787-07e9-091f-0aa37b0b61f7}" SpecialFunc="None">
    <Declaration><![CDATA[(* póki co ten FB jest zbędny ale zostawiam jakby co*)
FUNCTION_BLOCK FB_BaseHMILogger// EXTENDS FB_Base IMPLEMENTS ITF_BaseLoggerElement_HMI
VAR
//	itfBaseLoggerConnector			: ITF_BaseLogger_HMI_Connector;	//łącznik bezpośredni do Logera
//	refstBaseLoggerDataHMI			: REFERENCE TO ST_BaseLogger_HMI;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>